using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ToDo : MonoBehaviour
{
    /* TODO:
    CLEAN UP FOLDERS
        -ONE OF THE PLAYER HEALTH BAR SCRIPTS ISN'T BEING USED
    CREATE BASIC MAP
        -GET TILEMAP TOGETHER -- CHECK
        -PAINT TILEMAP
        -CREATE LADDERS -- HOLD
    CREATE PLAYER
        -IMPORT ASSETS -- CHECK
        -CREATE ANIMATIONS/STATE MACHINE -- CHECK
            - CHANGE COLLIDERS TO MATCH ANIMATIONS (DUCKING, ETC) -- CHECK
        -CREATE CONTROLLER -- CHECK
    CREATE BASIC ENEMY
        -GET ASSETS -- CHECK
        -CREATE ANIMATIONS/STATE MACHINE -- CHECK
        -CREATE BRAIN -- CHECK
    BASIC COMBAT
        -ADD PLAYER HEALTH -- CHECK
        -ADD ENEMY HEALTH -- CHECK
        -ADD COLLISIONS -- CHECK
    SOUNDS
        -FOOTSTEPS
        -COMBAT SOUNDS

    YOU ARE CURRENTLY TRYING TO FIGURE OUT HOW TO MAKE THE CHARACTER STOP RUNNING WHEN THEY PRESS THE ATTACK BUTTON
    */
}
