using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ToDo : MonoBehaviour
{
    /* TODO:
    
    SYNC UP TOOLBAR AND INVENTORY UIS SO ITEMS CAN BE ADDED/REMOVED FROM TOOLBAR -- MIGHT NOT DO THIS FOR OVERWORLD
    REFACTOR SPAWNERS TO POOLS
   IMPLIMENT FOG OF WAR
        EXPAND MAP
        IMPLIMENT FOG OF WAR IN EXTRA AREAS
        UNLOCK EXPANDED AREAS WITH MAPS
   TREASURE MAPS
        ADD TO ITEMDB
        ADD RARITY TO LOOT DROPS
        ADD HIDDEN "HIDDEN TREASURE" SPOTS THROUGHOUT THE MAP
        UNLOCK SPECIFIC HIDDEN TREASURE SPOTS WHEN PLAYER HOLDS A MAP
        RANDOMIZE MAP LOCATIONS
        ADD TREASURE MAPS TO APPEAR RANDOMLY IN SHOPS
    FIX MAIN MENU BUTTONS SO THAT THEY DON'T AUTOMATICALLY TRIGGER ON LOAD
    */
}
